# Generated by Django 5.2.7 on 2025-10-21 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens.', regex='^[a-z0-9-]+$')])),
                ('cloud_provider', models.CharField(choices=[('aws', 'Amazon Web Services'), ('gcp', 'Google Cloud Platform'), ('azure', 'Microsoft Azure')], max_length=20)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('account_id', models.CharField(blank=True, help_text='AWS Account ID, GCP Project ID, or Azure Subscription ID', max_length=50)),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
                'indexes': [models.Index(fields=['organization', 'cloud_provider'], name='environment_organiz_dd3932_idx'), models.Index(fields=['is_active'], name='environment_is_acti_82c5f0_idx')],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
