# Generated by Django 5.2.7 on 2025-10-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('aws_access_keys', 'AWS Access Keys'), ('aws_role', 'AWS IAM Role'), ('azure_service_principal', 'Azure Service Principal'), ('gcp_service_account', 'GCP Service Account')], max_length=30)),
                ('name', models.CharField(help_text='Credential name for easy identification', max_length=100)),
                ('aws_access_key_id', models.CharField(blank=True, max_length=128, null=True)),
                ('aws_secret_access_key', models.CharField(blank=True, max_length=128, null=True)),
                ('aws_role_arn', models.CharField(blank=True, max_length=200, null=True)),
                ('azure_client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('azure_client_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('azure_tenant_id', models.CharField(blank=True, max_length=128, null=True)),
                ('gcp_service_account_key', models.TextField(blank=True, help_text='GCP Service Account JSON key', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='environments.environment')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
