# Generated by Django 5.2.7 on 2025-10-21 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IACRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repository_url', models.URLField(help_text='Git repository URL containing IaC files', validators=[django.core.validators.URLValidator()])),
                ('branch', models.CharField(default='main', max_length=100)),
                ('tool', models.CharField(choices=[('terraform', 'Terraform'), ('cloudformation', 'AWS CloudFormation'), ('kubernetes', 'Kubernetes Manifests')], max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('credentials_encrypted', models.BinaryField(blank=True, help_text='Encrypted authentication credentials', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iac_repositories', to='environments.environment')),
            ],
            options={
                'ordering': ['environment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IACResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(help_text='Type of resource (e.g., "aws_instance", "kubernetes_deployment")', max_length=100)),
                ('resource_id', models.CharField(help_text='Unique identifier for the resource (Terraform address, etc.)', max_length=255)),
                ('declared_state', models.JSONField(help_text='Complete resource configuration from IaC definition')),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iac_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='iac.iacrepository')),
            ],
            options={
                'ordering': ['iac_repository', 'resource_type', 'resource_id'],
            },
        ),
        migrations.AddIndex(
            model_name='iacrepository',
            index=models.Index(fields=['environment', 'tool'], name='iac_iacrepo_environ_917bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='iacrepository',
            index=models.Index(fields=['last_sync_at'], name='iac_iacrepo_last_sy_0cd73b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='iacrepository',
            unique_together={('environment', 'repository_url', 'branch')},
        ),
        migrations.AddIndex(
            model_name='iacresource',
            index=models.Index(fields=['iac_repository', 'resource_type'], name='iac_iacreso_iac_rep_d719f6_idx'),
        ),
        migrations.AddIndex(
            model_name='iacresource',
            index=models.Index(fields=['last_sync_at'], name='iac_iacreso_last_sy_83697e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='iacresource',
            unique_together={('iac_repository', 'resource_id')},
        ),
    ]
