# Generated by Django 5.2.7 on 2025-10-22 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IaCFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the IaC file within the repository', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='File extension (e.g., .tf, .json, .yaml)', max_length=50)),
                ('content_hash', models.CharField(help_text='SHA256 hash of file content', max_length=64)),
                ('last_modified', models.DateTimeField(help_text='When file was last modified in repository')),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['file_path'],
            },
        ),
        migrations.AlterModelOptions(
            name='iacrepository',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='iacresource',
            options={'ordering': ['resource_type', 'resource_id']},
        ),
        migrations.RemoveIndex(
            model_name='iacrepository',
            name='iac_iacrepo_environ_917bc1_idx',
        ),
        migrations.RemoveIndex(
            model_name='iacrepository',
            name='iac_iacrepo_last_sy_0cd73b_idx',
        ),
        migrations.RemoveIndex(
            model_name='iacresource',
            name='iac_iacreso_iac_rep_d719f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='iacresource',
            name='iac_iacreso_last_sy_83697e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='iacrepository',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='iacrepository',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iacrepository',
            name='github_token',
            field=models.CharField(blank=True, help_text='GitHub personal access token', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='iacrepository',
            name='iac_type',
            field=models.CharField(choices=[('terraform', 'Terraform'), ('cloudformation', 'AWS CloudFormation'), ('arm_template', 'Azure ARM Template'), ('bicep', 'Azure Bicep'), ('pulumi', 'Pulumi'), ('cdk', 'AWS CDK')], default='terraform', max_length=20),
        ),
        migrations.AddField(
            model_name='iacrepository',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iacrepository',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iacrepository',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], default='github', max_length=20),
        ),
        migrations.AddField(
            model_name='iacrepository',
            name='repository_name',
            field=models.CharField(default=1, help_text='Repository name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iacrepository',
            name='repository_owner',
            field=models.CharField(default=1, help_text='Repository owner/organization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iacresource',
            name='line_number',
            field=models.IntegerField(default=0, help_text='Line number in the IaC file where resource is defined'),
        ),
        migrations.AddField(
            model_name='iacresource',
            name='provider',
            field=models.CharField(default='aws', help_text='Cloud provider (aws, azure, gcp)', max_length=20),
        ),
        migrations.AddField(
            model_name='iacresource',
            name='resource_definition',
            field=models.TextField(default=1, help_text='JSON representation of the resource definition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iacrepository',
            name='branch',
            field=models.CharField(default='main', help_text='Branch to monitor', max_length=100),
        ),
        migrations.AlterField(
            model_name='iacrepository',
            name='name',
            field=models.CharField(help_text='Descriptive name for this repository', max_length=100),
        ),
        migrations.AlterField(
            model_name='iacrepository',
            name='repository_url',
            field=models.URLField(help_text='Full URL to the repository'),
        ),
        migrations.AlterField(
            model_name='iacresource',
            name='resource_id',
            field=models.CharField(help_text='Unique identifier for the resource (e.g., resource name)', max_length=200),
        ),
        migrations.AlterField(
            model_name='iacresource',
            name='resource_type',
            field=models.CharField(choices=[('aws_instance', 'AWS EC2 Instance'), ('aws_s3_bucket', 'AWS S3 Bucket'), ('aws_rds_instance', 'AWS RDS Instance'), ('aws_lambda_function', 'AWS Lambda Function'), ('aws_security_group', 'AWS Security Group'), ('aws_load_balancer', 'AWS Load Balancer'), ('azurerm_virtual_machine', 'Azure Virtual Machine'), ('azurerm_storage_account', 'Azure Storage Account'), ('azurerm_sql_database', 'Azure SQL Database'), ('azurerm_app_service', 'Azure App Service'), ('azurerm_network_security_group', 'Azure NSG'), ('azurerm_load_balancer', 'Azure Load Balancer'), ('other', 'Other Resource')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='iacfile',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='iac.iacrepository'),
        ),
        migrations.AlterUniqueTogether(
            name='iacresource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='iacresource',
            name='iac_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='iac.iacfile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='iacresource',
            unique_together={('iac_file', 'resource_id')},
        ),
        migrations.RemoveField(
            model_name='iacrepository',
            name='credentials_encrypted',
        ),
        migrations.RemoveField(
            model_name='iacrepository',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='iacrepository',
            name='last_sync_at',
        ),
        migrations.RemoveField(
            model_name='iacrepository',
            name='tool',
        ),
        migrations.AlterUniqueTogether(
            name='iacfile',
            unique_together={('repository', 'file_path')},
        ),
        migrations.RemoveField(
            model_name='iacresource',
            name='declared_state',
        ),
        migrations.RemoveField(
            model_name='iacresource',
            name='iac_repository',
        ),
        migrations.RemoveField(
            model_name='iacresource',
            name='last_sync_at',
        ),
    ]
