# Generated by Django 5.2.7 on 2025-10-21 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriftChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_path', models.CharField(help_text='JSON path to the changed property', max_length=500)),
                ('declared_value', models.JSONField(blank=True, help_text='Value in IaC declaration', null=True)),
                ('actual_value', models.JSONField(blank=True, help_text='Actual value in cloud provider', null=True)),
                ('change_type', models.CharField(choices=[('modified', 'Property Modified'), ('added', 'Property Added'), ('removed', 'Property Removed')], max_length=20)),
                ('is_security_critical', models.BooleanField(default=False, help_text='Whether this change poses a security risk')),
                ('change_impact', models.JSONField(blank=True, default=dict, help_text='Impact assessment for this specific change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_security_critical', 'property_path'],
            },
        ),
        migrations.CreateModel(
            name='DriftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drift_type', models.CharField(choices=[('modified', 'Configuration Modified'), ('deleted', 'Resource Deleted'), ('added', 'New Resource Added'), ('moved', 'Resource Moved')], max_length=20)),
                ('actual_state', models.JSONField(blank=True, help_text='Current state of the resource in cloud provider', null=True)),
                ('declared_state', models.JSONField(help_text='State as defined in IaC at time of detection')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('auto_revert', 'Automatically Reverted'), ('codify_iac', 'Updated IaC'), ('accepted', 'Accepted Drift'), ('escalated', 'Escalated for Review')], max_length=20, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('severity_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall severity score (0.0-1.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Confidence in detection accuracy (0.0-1.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_assessment', models.JSONField(blank=True, default=dict, help_text='JSON object with security, performance, cost, compliance impacts')),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Additional tags and metadata')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Detailed metadata about the drift event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-detected_at', '-severity_score'],
            },
        ),
    ]
