# Generated by Django 5.2.7 on 2025-10-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drifts', '0001_initial'),
        ('environments', '0001_initial'),
        ('iac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftevent',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drifts', to='environments.environment'),
        ),
        migrations.AddField(
            model_name='driftevent',
            name='iac_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift', to='iac.iacresource'),
        ),
        migrations.AddField(
            model_name='driftchange',
            name='drift_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='drifts.driftevent'),
        ),
        migrations.AddIndex(
            model_name='driftevent',
            index=models.Index(fields=['environment', 'detected_at'], name='drifts_drif_environ_1d5672_idx'),
        ),
        migrations.AddIndex(
            model_name='driftevent',
            index=models.Index(fields=['iac_resource', 'resolved_at'], name='drifts_drif_iac_res_cb76b9_idx'),
        ),
        migrations.AddIndex(
            model_name='driftevent',
            index=models.Index(fields=['drift_type', 'severity_score'], name='drifts_drif_drift_t_2453ff_idx'),
        ),
        migrations.AddIndex(
            model_name='driftevent',
            index=models.Index(fields=['resolved_at'], name='drifts_drif_resolve_1e0efc_idx'),
        ),
        migrations.AddIndex(
            model_name='driftchange',
            index=models.Index(fields=['drift_event', 'is_security_critical'], name='drifts_drif_drift_e_c947d3_idx'),
        ),
        migrations.AddIndex(
            model_name='driftchange',
            index=models.Index(fields=['property_path'], name='drifts_drif_propert_aad86d_idx'),
        ),
    ]
